// Even Fibonacci Numbers
//
// Each new term in the Fibonacci sequence is generated by adding the previous
// two terms. By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not
// exceed four million, find the sum of the even-valued terms.


class problem002 {
  private static int n1 = 0;
  private static int n2 = 1;
  private static int sum = 0;
  private static int MAXVALUE = 4000000;
  
  public static void incrementValues() {
    int temp = n1 + n2;
    n1 = n2;
    n2 = temp;
  }
  
  public static void incrementSum() {
    if (n2 % 2 == 0) sum += n2;
  }
  
  public static void main(String[] args) {
    while (n2 < MAXVALUE) {
      incrementValues();
      incrementSum();
    }
    System.out.println(sum);
  }
}
